-- Surface Area and Volume of a Box
-- https://www.codewars.com/kata/565f5825379664a26b00007c

SELECT WIDTH, HEIGHT, DEPTH, 2 * (WIDTH * HEIGHT + DEPTH * WIDTH + DEPTH * HEIGHT) AS AREA, WIDTH * HEIGHT * DEPTH AS VOLUME
FROM BOX
ORDER BY AREA ASC, VOLUME DESC, WIDTH ASC, HEIGHT ASC;